### ISSUE TITLE
Fullstack capstone

### ISSUE THREAD

**Issue by skabeo** [skabeo/backend_capstone#16]
- In this project we have four contributors:
  -  @juanmanuelbyc 
  -  @yegonkimutai 
  - @skabeo 
  - @adeola003 

You can view the link to our Kanban board [here](https://github.com/skabeo/backend_capstone/projects/1)

Kanban screenshot
![image](https://github.com/skabeo/backend_capstone/assets/118059164/230456c8-3006-4a81-a594-2e363d2d3061)

**Comment by Meltrust** [comment]
Hi @skabeo,

## Wow, you did it 🎉 
![Brilliant](https://media.giphy.com/media/d31w24psGYeekCZy/giphy.gif)

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

### To highlight

- Great job! ✔️ 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
